<a href="https://colab.research.google.com/github/Fentahun60/Fentahun/blob/main/ART_adherance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [700]:
import os
import pandas as pd
import gdown

# New file ID from the link provided
file_id = '1gpFpAdJ1XSau_7IyFs-y0AqCNLykFRlA'
output_filename = 'downloaded_file.csv'

# Force a fresh download for the new link
if os.path.exists(output_filename):
    os.remove(output_filename)

# Download the file using gdown
gdown.download(id=file_id, output=output_filename, quiet=False)

# Using robust loading logic developed previously
try:
    df1 = pd.read_csv(output_filename, sep=None, engine='python', on_bad_lines='warn', encoding='utf-8')
except (UnicodeDecodeError, pd.errors.ParserError):
    df1 = pd.read_csv(output_filename, sep=None, engine='python', on_bad_lines='warn', encoding='latin1')

print("File loaded into df1 successfully.")
df1.head()

Downloading...
From: https://drive.google.com/uc?id=1gpFpAdJ1XSau_7IyFs-y0AqCNLykFRlA
To: /content/downloaded_file.csv
100%|██████████| 1.84M/1.84M [00:00<00:00, 195MB/s]

File loaded into df1 successfully.

,PatientGUID,Health Facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,000552850770442ba548fb1bdc6c8d5a,ALERT,M,61.0,49,NaN,10-10-09,26-11-09,181,07-11-24,...,NaN,Yes,Negative,17-05-24,Suppressed,NaN,06-05-24,06-05-24,Appointment Spacing Model (ASM)/6MMD,No
1,00080b1139174e14abfa31e899bbb7e1,ALERT,M,NaN,51,177.0,14-12-09,10-10-13,134,10-12-24,...,NaN,Yes,Negative,26-09-24,Suppressed,NaN,20-06-24,20-06-24,NaN,No
2,0018c84fc44a428ba5cc6d0b2b62312e,ALERT,F,63.0,72,163.0,26-10-03,26-10-03,254,30-08-24,...,Good,Yes,Negative,25-03-24,Suppressed,NaN,04-03-24,04-03-24,NaN,No
3,001de407f0754eba8f2b577b7636f857,ALERT,M,80.0,53,170.0,14-03-11,05-09-11,159,07-09-24,...,Good,Yes,Negative,01-11-24,Suppressed,NaN,07-09-24,07-09-24,Appointment Spacing Model (ASM)/6MMD,No
4,001f9d5a3a2d40a190fca88c36f893cf,ALERT,F,63.0,54,153.0,02-01-00,15-12-15,108,14-12-24,...,NaN,Yes,Negative,26-12-23,Suppressed,NaN,14-12-24,14-12-24,Appointment Spacing Model (ASM)/6MMD,No

In [701]:
df1.columns

Index(['PatientGUID', 'Health Facility', 'Sex', 'Weight', 'Age', 'Height',
       'date_hiv_confirmed', 'art_start_date', 'MonthsOnART', 'FollowUpDate',
       'WHO', 'CD4', 'ARTDoseDays', 'ARVRegimen', 'follow_up_status',
       'AdheranceLevel', 'NutritionalStatus', 'FunctionalStatus', 'No_OI',
       'CotrimoxazoleStartDate', 'cortimoxazole_stop_date', 'TPT_Type',
       'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
       'TPT_DoseDaysNumberALT', 'TPT_DoseDaysNumberINH', 'TPT_Dispensed_Dose',
       'TPT_SideEffect', 'TPT_Adherence', 'tb_screened', 'tb_screening_result',
       'viral_load_perform_date', 'viral_load_status', 'viral_load_count',
       'VL_Sent_Date', 'viral_load_ref_date', 'DSD_Category', 'AHD'],
      dtype='object')

In [702]:
df1.shape

(6472, 38)

In [703]:
import os
import pandas as pd
import gdown

# New file ID from the link provided
file_id_2 = '1r9Nho8Q_814vFUND1RjmVQvRDHF36yr1'
output_filename_2 = 'downloaded_file_2.csv'

# Remove existing file to ensure a fresh download from the link
if os.path.exists(output_filename_2):
    os.remove(output_filename_2)

# Download the file from Google Drive
gdown.download(id=file_id_2, output=output_filename_2, quiet=False)

# Load into df2 with robust error handling
try:
    df2 = pd.read_csv(output_filename_2, sep=None, engine='python', on_bad_lines='warn', encoding='utf-8')
except (UnicodeDecodeError, pd.errors.ParserError):
    df2 = pd.read_csv(output_filename_2, sep=None, engine='python', on_bad_lines='warn', encoding='latin1')

print("File loaded into df2 successfully.")
df2.head()

Downloading...
From: https://drive.google.com/uc?id=1r9Nho8Q_814vFUND1RjmVQvRDHF36yr1
To: /content/downloaded_file_2.csv
100%|██████████| 289k/289k [00:00<00:00, 79.7MB/s]

File loaded into df2 successfully.

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,CCA_Screened,DSD_Category,AHD,Id,PatientId
0,ac48adf3d2e5419d87e2d92518777939,ALERT,F,50.0,30,166.0,22-02-06,14-04-06,224,24-12-24,...,09-04-24,Suppressed,NaN,28-03-24,28-03-24,NaN,NaN,No,160870,1402
1,3976a9c2e0fd44f783aeabea6a0d94c9,ALERT,M,40.0,23,157.0,14-09-05,22-07-06,221,01-12-24,...,14-09-23,Suppressed,NaN,01-09-24,01-09-24,NaN,PCAD (Community Based Group model led by Peer),No,160211,1434
2,6629bdacd9064183b4dd908d2b29b599,ALERT,F,46.0,20,161.0,20-07-06,09-01-07,215,07-12-24,...,04-12-24,Suppressed,NaN,09-11-24,09-11-24,NaN,3MMD,No,160863,1500
3,e306d04b91254f65bc007823f4c36dd5,ALERT,F,43.0,26,165.0,20-10-01,21-02-07,214,27-11-24,...,30-10-24,Suppressed,NaN,28-08-24,28-08-24,NaN,Appointment Spacing Model (ASM)/6MMD,No,160038,1535
4,7abb3e204da8493f9ffaa26e316fe342,ALERT,F,43.0,25,151.0,02-01-00,25-07-05,233,11-12-24,...,13-06-22,Suppressed,NaN,28-05-22,28-05-22,NaN,HEP-CAG(Health Extension Professional Led Comm...,No,160564,1364

In [704]:
selected_columns = [
    'PatientGUID', 'Health_facility', 'Sex', 'Weight', 'Age', 'Height',
    'date_hiv_confirmed', 'art_start_date', 'MonthsOnART', 'FollowUpDate',
    'WHO', 'CD4', 'ARTDoseDays', 'ARVRegimen', 'follow_up_status',
    'AdheranceLevel', 'NutritionalStatus', 'FunctionalStatus', 'No_OI',
    'CotrimoxazoleStartDate', 'cortimoxazole_stop_date', 'TPT_Type',
    'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
    'TPT_DoseDaysNumberALT', 'TPT_DoseDaysNumberINH', 'TPT_Dispensed_Dose',
    'TPT_SideEffect', 'TPT_Adherence', 'tb_screened', 'tb_screening_result',
    'viral_load_perform_date', 'viral_load_status', 'viral_load_count',
    'VL_Sent_Date', 'viral_load_ref_date', 'DSD_Category', 'AHD'
]

# Filter df2 and display the head of the resulting DataFrame
df2_final = df2[selected_columns]
df2_final.head()

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,ac48adf3d2e5419d87e2d92518777939,ALERT,F,50.0,30,166.0,22-02-06,14-04-06,224,24-12-24,...,Good,Yes,Negative,09-04-24,Suppressed,NaN,28-03-24,28-03-24,NaN,No
1,3976a9c2e0fd44f783aeabea6a0d94c9,ALERT,M,40.0,23,157.0,14-09-05,22-07-06,221,01-12-24,...,NaN,Yes,Negative,14-09-23,Suppressed,NaN,01-09-24,01-09-24,PCAD (Community Based Group model led by Peer),No
2,6629bdacd9064183b4dd908d2b29b599,ALERT,F,46.0,20,161.0,20-07-06,09-01-07,215,07-12-24,...,NaN,Yes,Negative,04-12-24,Suppressed,NaN,09-11-24,09-11-24,3MMD,No
3,e306d04b91254f65bc007823f4c36dd5,ALERT,F,43.0,26,165.0,20-10-01,21-02-07,214,27-11-24,...,NaN,Yes,Negative,30-10-24,Suppressed,NaN,28-08-24,28-08-24,Appointment Spacing Model (ASM)/6MMD,No
4,7abb3e204da8493f9ffaa26e316fe342,ALERT,F,43.0,25,151.0,02-01-00,25-07-05,233,11-12-24,...,NaN,Yes,Negative,13-06-22,Suppressed,NaN,28-05-22,28-05-22,HEP-CAG(Health Extension Professional Led Comm...,No

In [705]:
df2_final.shape

(914, 38)

In [706]:
import os
import pandas as pd
import gdown

# New file ID from the link provided
file_id_3 = '1VCiaHcvZot7N2l3NsU_xriij8g84-8Uk'
output_filename_3 = 'downloaded_file_3.csv'

# Remove existing file to ensure a fresh download from the new link
if os.path.exists(output_filename_3):
    os.remove(output_filename_3)

# Download the file from Google Drive
gdown.download(id=file_id_3, output=output_filename_3, quiet=False)

# Load into df3 with robust error handling for encoding and delimiters
try:
    df3 = pd.read_csv(output_filename_3, sep=None, engine='python', on_bad_lines='warn', encoding='utf-8')
except (UnicodeDecodeError, pd.errors.ParserError):
    df3 = pd.read_csv(output_filename_3, sep=None, engine='python', on_bad_lines='warn', encoding='latin1')

print("File loaded into df3 successfully.")
df3.head()

Downloading...
From: https://drive.google.com/uc?id=1VCiaHcvZot7N2l3NsU_xriij8g84-8Uk
To: /content/downloaded_file_3.csv
100%|██████████| 77.1k/77.1k [00:00<00:00, 53.7MB/s]

File loaded into df3 successfully.

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,CCA_Screened,DSD_Category,AHD,Id,PatientId
0,35a4b38de549449c80249b7259ccd0c3,Yekatit 12,F,42.0,16,152.0,19-02-15,19-02-15,118,19-10-24,...,31-03-23,Suppressed,20.0,20-03-24,20-03-24,NaN,DSD for Adolescent,No,182055,5223
1,3719525d32d24933ab3814d76cb44bc5,Yekatit 13,F,63.0,16,153.0,21-11-12,04-12-12,144,12-10-24,...,20-03-24,Suppressed,0.0,08-03-24,08-03-24,NaN,3MMD,No,182013,2487
2,425fa5c7c0b94408ae02ff742b75a79b,Yekatit 14,F,45.0,16,133.0,16-10-08,17-10-08,194,06-10-24,...,24-11-23,Suppressed,0.0,28-10-23,28-10-23,NaN,3MMD,No,182002,3316
3,530af9f55db84209802489ac4db7d77a,Yekatit 15,F,52.0,16,152.0,15-07-11,03-08-11,160,12-12-24,...,12-01-24,Suppressed,0.0,16-12-23,16-12-23,NaN,3MMD,No,182834,2448
4,6fe0d5dd25eb4acd81fd1d4de1be5ba1,Yekatit 16,F,35.0,16,155.0,25-07-14,01-10-15,110,10-11-24,...,05-12-24,Suppressed,0.0,10-11-24,10-11-24,NaN,3MMD,No,182746,23373

In [707]:
columns_to_select = [
    'PatientGUID', 'Health_facility', 'Sex', 'Weight', 'Age', 'Height',
    'date_hiv_confirmed', 'art_start_date', 'MonthsOnART', 'FollowUpDate',
    'WHO', 'CD4', 'ARTDoseDays', 'ARVRegimen', 'follow_up_status',
    'AdheranceLevel', 'NutritionalStatus', 'FunctionalStatus', 'No_OI',
    'CotrimoxazoleStartDate', 'cortimoxazole_stop_date', 'TPT_Type',
    'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
    'TPT_DoseDaysNumberALT', 'TPT_DoseDaysNumberINH', 'TPT_Dispensed_Dose',
    'TPT_SideEffect', 'TPT_Adherence', 'tb_screened', 'tb_screening_result',
    'viral_load_perform_date', 'viral_load_status', 'viral_load_count',
    'VL_Sent_Date', 'viral_load_ref_date', 'DSD_Category', 'AHD'
]

# Filtering df3
df3_final = df3[columns_to_select]

# Display the head of the updated df3
df3_final.head()

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,35a4b38de549449c80249b7259ccd0c3,Yekatit 12,F,42.0,16,152.0,19-02-15,19-02-15,118,19-10-24,...,NaN,Yes,Negative,31-03-23,Suppressed,20.0,20-03-24,20-03-24,DSD for Adolescent,No
1,3719525d32d24933ab3814d76cb44bc5,Yekatit 13,F,63.0,16,153.0,21-11-12,04-12-12,144,12-10-24,...,NaN,Yes,Negative,20-03-24,Suppressed,0.0,08-03-24,08-03-24,3MMD,No
2,425fa5c7c0b94408ae02ff742b75a79b,Yekatit 14,F,45.0,16,133.0,16-10-08,17-10-08,194,06-10-24,...,NaN,Yes,Negative,24-11-23,Suppressed,0.0,28-10-23,28-10-23,3MMD,No
3,530af9f55db84209802489ac4db7d77a,Yekatit 15,F,52.0,16,152.0,15-07-11,03-08-11,160,12-12-24,...,NaN,Yes,Negative,12-01-24,Suppressed,0.0,16-12-23,16-12-23,3MMD,No
4,6fe0d5dd25eb4acd81fd1d4de1be5ba1,Yekatit 16,F,35.0,16,155.0,25-07-14,01-10-15,110,10-11-24,...,Good,Yes,Negative,05-12-24,Suppressed,0.0,10-11-24,10-11-24,3MMD,No

In [708]:
df3_final.shape

(253, 38)

In [709]:
import os
import pandas as pd
import gdown

# New file ID from the link provided
file_id_4 = '1COeBQfQI93Bq8m47SwuyGjLGU9RLXQun'
output_filename_4 = 'downloaded_file_4.csv'

# Remove existing file to ensure a fresh download from the link
if os.path.exists(output_filename_4):
    os.remove(output_filename_4)

# Download the file from Google Drive
gdown.download(id=file_id_4, output=output_filename_4, quiet=False)

# Load into df4 with robust error handling
try:
    df4 = pd.read_csv(output_filename_4, sep=None, engine='python', on_bad_lines='warn', encoding='utf-8')
except (UnicodeDecodeError, pd.errors.ParserError):
    df4 = pd.read_csv(output_filename_4, sep=None, engine='python', on_bad_lines='warn', encoding='latin1')

print("File loaded into df4 successfully.")
df4.head()

Downloading...
From: https://drive.google.com/uc?id=1COeBQfQI93Bq8m47SwuyGjLGU9RLXQun
To: /content/downloaded_file_4.csv
100%|██████████| 978k/978k [00:00<00:00, 165MB/s]

File loaded into df4 successfully.

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,CCA_Screened,DSD_Category,AHD,Id,PatientId
0,a29ee9c8d3f1432dbf39f3e69203c1ac,Yekatit,F,NaN,42,NaN,03-12-07,03-06-17,90,03-12-24,...,02-01-00,NaN,NaN,09-08-23,09-08-23,NaN,3MMD,No,709356,541339
1,a9b35739f46541128784c8795076014f,Yekatit,F,46.0,42,158.0,29-10-07,29-02-08,202,23-09-24,...,29-03-24,Suppressed,0.0,20-02-24,20-02-24,Yes,Appointment Spacing Model (ASM)/6MMD,No,682511,8415
2,aa50aa72145b4176ad8e999aa20b7b1a,Yekatit,F,53.0,42,164.0,15-09-20,15-09-20,51,21-09-24,...,17-04-24,Suppressed,0.0,01-03-24,01-03-24,Yes,3MMD,No,682412,419965
3,afd5b18921cc44e48fe70e1e4d5e5b6e,Yekatit,M,75.0,42,175.0,13-11-14,10-02-15,118,26-11-24,...,20-08-24,Low Level Viremia,56.0,26-07-24,26-07-24,NaN,3MMD,No,703501,600198
4,b0511069305b4799bcffc265ea86729e,Yekatit,M,NaN,42,165.0,09-04-08,23-04-08,200,02-11-24,...,30-10-24,Suppressed,0.0,15-09-24,15-09-24,NaN,3MMD,No,698359,10703

In [710]:
columns_to_select_df4 = [
    'PatientGUID', 'Health_facility', 'Sex', 'Weight', 'Age', 'Height',
    'date_hiv_confirmed', 'art_start_date', 'MonthsOnART', 'FollowUpDate',
    'WHO', 'CD4', 'ARTDoseDays', 'ARVRegimen', 'follow_up_status',
    'AdheranceLevel', 'NutritionalStatus', 'FunctionalStatus', 'No_OI',
    'CotrimoxazoleStartDate', 'cortimoxazole_stop_date', 'TPT_Type',
    'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
    'TPT_DoseDaysNumberALT', 'TPT_DoseDaysNumberINH', 'TPT_Dispensed_Dose',
    'TPT_SideEffect', 'TPT_Adherence', 'tb_screened', 'tb_screening_result',
    'viral_load_perform_date', 'viral_load_status', 'viral_load_count',
    'VL_Sent_Date', 'viral_load_ref_date', 'DSD_Category', 'AHD'
]

# Filtering df4
df4_final = df4[columns_to_select_df4]

# Display the head of the updated df4
df4_final.head()

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,a29ee9c8d3f1432dbf39f3e69203c1ac,Yekatit,F,NaN,42,NaN,03-12-07,03-06-17,90,03-12-24,...,NaN,Yes,Negative,02-01-00,NaN,NaN,09-08-23,09-08-23,3MMD,No
1,a9b35739f46541128784c8795076014f,Yekatit,F,46.0,42,158.0,29-10-07,29-02-08,202,23-09-24,...,NaN,Yes,Negative,29-03-24,Suppressed,0.0,20-02-24,20-02-24,Appointment Spacing Model (ASM)/6MMD,No
2,aa50aa72145b4176ad8e999aa20b7b1a,Yekatit,F,53.0,42,164.0,15-09-20,15-09-20,51,21-09-24,...,NaN,Yes,Negative,17-04-24,Suppressed,0.0,01-03-24,01-03-24,3MMD,No
3,afd5b18921cc44e48fe70e1e4d5e5b6e,Yekatit,M,75.0,42,175.0,13-11-14,10-02-15,118,26-11-24,...,NaN,Yes,Negative,20-08-24,Low Level Viremia,56.0,26-07-24,26-07-24,3MMD,No
4,b0511069305b4799bcffc265ea86729e,Yekatit,M,NaN,42,165.0,09-04-08,23-04-08,200,02-11-24,...,NaN,Yes,Negative,30-10-24,Suppressed,0.0,15-09-24,15-09-24,3MMD,No

In [711]:
df4_final.shape

(3155, 38)

In [712]:
import os
import pandas as pd
import gdown

# New file ID from the link provided
file_id_5 = '1yYPzupEYridsV9Gq0ONG_Mg2VsA6vIcs'
output_filename_5 = 'downloaded_file_5.csv'

# Remove existing file to ensure a fresh download from the link
if os.path.exists(output_filename_5):
    os.remove(output_filename_5)

# Download the file from Google Drive
gdown.download(id=file_id_5, output=output_filename_5, quiet=False)

# Load into df5 with robust error handling
try:
    df5 = pd.read_csv(output_filename_5, sep=None, engine='python', on_bad_lines='warn', encoding='utf-8')
except (UnicodeDecodeError, pd.errors.ParserError):
    df5 = pd.read_csv(output_filename_5, sep=None, engine='python', on_bad_lines='warn', encoding='latin1')

print("File loaded into df5 successfully.")
df5.head()

Downloading...
From: https://drive.google.com/uc?id=1yYPzupEYridsV9Gq0ONG_Mg2VsA6vIcs
To: /content/downloaded_file_5.csv
100%|██████████| 2.51M/2.51M [00:00<00:00, 259MB/s]

File loaded into df5 successfully.

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,CCA_Screened,DSD_Category,AHD,Id,PatientId
0,f09e6ebafa76469f9b70664dc43051f0,Zewditu,F,NaN,57,158.0,19-03-99,20-10-09,182,28-10-24,...,19-04-24,Suppressed,0.0,02-04-24,02-04-24,NaN,NaN,No,1782448,91022
1,f3cebc448b594f999f3e03db01728658,Zewditu,M,72.0,57,173.0,04-10-06,12-10-07,206,25-12-24,...,02-04-24,Suppressed,0.0,04-03-24,04-03-24,NaN,Appointment Spacing Model (ASM)/6MMD,No,1797383,5840
2,f401fa9e5f9d44d6876746e72cb4b36f,Zewditu,F,69.0,57,156.0,21-12-06,01-01-07,215,17-09-24,...,06-03-24,Suppressed,0.0,18-01-24,18-01-24,Yes,Appointment Spacing Model (ASM)/6MMD,No,1791091,4755
3,f67d372c7a70456fbcd1c582e3a4f431,Zewditu,F,75.0,57,166.0,19-04-05,19-04-05,236,21-06-24,...,03-07-24,Suppressed,0.0,05-06-24,05-06-24,NaN,NaN,No,1746388,1864
4,f7793f5da8e9489fa6bbbdbcc63daa02,Zewditu,F,72.0,57,NaN,21-10-10,20-11-24,1,20-11-24,...,09-12-24,Suppressed,NaN,20-11-24,20-11-24,NaN,NaN,No,1792746,1600347

In [713]:
columns_to_select_df5 = [
    'PatientGUID', 'Health_facility', 'Sex', 'Weight', 'Age', 'Height',
    'date_hiv_confirmed', 'art_start_date', 'MonthsOnART', 'FollowUpDate',
    'WHO', 'CD4', 'ARTDoseDays', 'ARVRegimen', 'follow_up_status',
    'AdheranceLevel', 'NutritionalStatus', 'FunctionalStatus', 'No_OI',
    'CotrimoxazoleStartDate', 'cortimoxazole_stop_date', 'TPT_Type',
    'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
    'TPT_DoseDaysNumberALT', 'TPT_DoseDaysNumberINH', 'TPT_Dispensed_Dose',
    'TPT_SideEffect', 'TPT_Adherence', 'tb_screened', 'tb_screening_result',
    'viral_load_perform_date', 'viral_load_status', 'viral_load_count',
    'VL_Sent_Date', 'viral_load_ref_date', 'DSD_Category', 'AHD'
]

# Filter df5
df5_final = df5[columns_to_select_df5]

# Display the head of the updated df5
df5_final.head()

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,f09e6ebafa76469f9b70664dc43051f0,Zewditu,F,NaN,57,158.0,19-03-99,20-10-09,182,28-10-24,...,NaN,Yes,Negative,19-04-24,Suppressed,0.0,02-04-24,02-04-24,NaN,No
1,f3cebc448b594f999f3e03db01728658,Zewditu,M,72.0,57,173.0,04-10-06,12-10-07,206,25-12-24,...,NaN,Yes,Negative,02-04-24,Suppressed,0.0,04-03-24,04-03-24,Appointment Spacing Model (ASM)/6MMD,No
2,f401fa9e5f9d44d6876746e72cb4b36f,Zewditu,F,69.0,57,156.0,21-12-06,01-01-07,215,17-09-24,...,NaN,Yes,Negative,06-03-24,Suppressed,0.0,18-01-24,18-01-24,Appointment Spacing Model (ASM)/6MMD,No
3,f67d372c7a70456fbcd1c582e3a4f431,Zewditu,F,75.0,57,166.0,19-04-05,19-04-05,236,21-06-24,...,NaN,Yes,Negative,03-07-24,Suppressed,0.0,05-06-24,05-06-24,NaN,No
4,f7793f5da8e9489fa6bbbdbcc63daa02,Zewditu,F,72.0,57,NaN,21-10-10,20-11-24,1,20-11-24,...,NaN,Yes,Negative,09-12-24,Suppressed,NaN,20-11-24,20-11-24,NaN,No

In [714]:
df5_final.shape

(7599, 38)

In [715]:
# Rename column in df1 to match the other dataframes
df1 = df1.rename(columns={'Health Facility': 'Health_facility'})

# List of dataframes to append
dfs_to_combine = [df1, df2_final, df3_final, df4_final, df5_final]

# Concatenate all dataframes
df_combined = pd.concat(dfs_to_combine, ignore_index=True)

# Display summary info
print(f"Combined DataFrame shape: {df_combined.shape}")
print("Dataframes appended successfully.")
df_combined.head()

Combined DataFrame shape: (18393, 38)
Dataframes appended successfully.

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,000552850770442ba548fb1bdc6c8d5a,ALERT,M,61.0,49,NaN,10-10-09,26-11-09,181,07-11-24,...,NaN,Yes,Negative,17-05-24,Suppressed,NaN,06-05-24,06-05-24,Appointment Spacing Model (ASM)/6MMD,No
1,00080b1139174e14abfa31e899bbb7e1,ALERT,M,NaN,51,177.0,14-12-09,10-10-13,134,10-12-24,...,NaN,Yes,Negative,26-09-24,Suppressed,NaN,20-06-24,20-06-24,NaN,No
2,0018c84fc44a428ba5cc6d0b2b62312e,ALERT,F,63.0,72,163.0,26-10-03,26-10-03,254,30-08-24,...,Good,Yes,Negative,25-03-24,Suppressed,NaN,04-03-24,04-03-24,NaN,No
3,001de407f0754eba8f2b577b7636f857,ALERT,M,80.0,53,170.0,14-03-11,05-09-11,159,07-09-24,...,Good,Yes,Negative,01-11-24,Suppressed,NaN,07-09-24,07-09-24,Appointment Spacing Model (ASM)/6MMD,No
4,001f9d5a3a2d40a190fca88c36f893cf,ALERT,F,63.0,54,153.0,02-01-00,15-12-15,108,14-12-24,...,NaN,Yes,Negative,26-12-23,Suppressed,NaN,14-12-24,14-12-24,Appointment Spacing Model (ASM)/6MMD,No

In [716]:
# Clean and standardize Health_facility names
def standardize_facility(name):
    name = str(name).strip()
    if 'ALERT' in name.upper():
        return 'ALERT'
    elif 'ZEW' in name.upper():
        return 'Zewuditu'
    elif 'YEK' in name.upper():
        return 'Yekatit'
    return name

df_combined['Health_facility'] = df_combined['Health_facility'].apply(standardize_facility)

# Check the unique values to verify the change
print("Standardized Health Facilities:")
print(df_combined['Health_facility'].unique())
print(f"\nValue counts:\n{df_combined['Health_facility'].value_counts()}")

Standardized Health Facilities:
['ALERT' 'Yekatit' 'Zewuditu']

Value counts:
Health_facility
Zewuditu    7599
ALERT       7386
Yekatit     3408
Name: count, dtype: int64

In [717]:
df_combined.shape

(18393, 38)

In [718]:
# Calculate proportions of the 'Sex' column
sex_proportions = df_combined['Sex'].value_counts(normalize=True) * 100

print("Proportion of Sex (%):")
print(sex_proportions)

# Also show raw counts for context
print("\nRaw counts:")
print(df_combined['Sex'].value_counts())

Proportion of Sex (%):
Sex
F    60.093514
M    39.906486
Name: proportion, dtype: float64

Raw counts:
Sex
F    11053
M     7340
Name: count, dtype: int64

In [719]:
# Identify potential date columns
date_columns = [
    'date_hiv_confirmed', 'art_start_date', 'FollowUpDate',
    'CotrimoxazoleStartDate', 'cortimoxazole_stop_date',
    'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
    'viral_load_perform_date', 'VL_Sent_Date', 'viral_load_ref_date'
]

# Convert identified columns to datetime
for col in date_columns:
    if col in df_combined.columns:
        df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')

# Verify the conversion
print("Data types for date columns:")
print(df_combined[date_columns].dtypes)
print("\nNumber of successfully parsed dates per column:")
print(df_combined[date_columns].notna().sum())
df_combined.head()

/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')

Data types for date columns:
date_hiv_confirmed             datetime64[ns]
art_start_date                 datetime64[ns]
FollowUpDate                   datetime64[ns]
CotrimoxazoleStartDate         datetime64[ns]
cortimoxazole_stop_date        datetime64[ns]
inhprophylaxis_started_date    datetime64[ns]
InhprophylaxisCompletedDate    datetime64[ns]
viral_load_perform_date        datetime64[ns]
VL_Sent_Date                   datetime64[ns]
viral_load_ref_date            datetime64[ns]
dtype: object

Number of successfully parsed dates per column:
date_hiv_confirmed             18393
art_start_date                 18393
FollowUpDate                   18393
CotrimoxazoleStartDate         18393
cortimoxazole_stop_date        18393
inhprophylaxis_started_date    16143
InhprophylaxisCompletedDate    15985
viral_load_perform_date        18393
VL_Sent_Date                   18064
viral_load_ref_date            18393
dtype: int64

/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')
/tmp/ipykernel_2725/2900117577.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined[col] = pd.to_datetime(df_combined[col], dayfirst=True, errors='coerce')

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,...,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,000552850770442ba548fb1bdc6c8d5a,ALERT,M,61.0,49,NaN,2009-10-10,2009-11-26,181,2024-11-07,...,NaN,Yes,Negative,2024-05-17,Suppressed,NaN,2024-05-06,2024-05-06,Appointment Spacing Model (ASM)/6MMD,No
1,00080b1139174e14abfa31e899bbb7e1,ALERT,M,NaN,51,177.0,2009-12-14,2013-10-10,134,2024-12-10,...,NaN,Yes,Negative,2024-09-26,Suppressed,NaN,2024-06-20,2024-06-20,NaN,No
2,0018c84fc44a428ba5cc6d0b2b62312e,ALERT,F,63.0,72,163.0,2003-10-26,2003-10-26,254,2024-08-30,...,Good,Yes,Negative,2024-03-25,Suppressed,NaN,2024-03-04,2024-03-04,NaN,No
3,001de407f0754eba8f2b577b7636f857,ALERT,M,80.0,53,170.0,2011-03-14,2011-09-05,159,2024-09-07,...,Good,Yes,Negative,2024-11-01,Suppressed,NaN,2024-09-07,2024-09-07,Appointment Spacing Model (ASM)/6MMD,No
4,001f9d5a3a2d40a190fca88c36f893cf,ALERT,F,63.0,54,153.0,2000-01-02,2015-12-15,108,2024-12-14,...,NaN,Yes,Negative,2023-12-26,Suppressed,NaN,2024-12-14,2024-12-14,Appointment Spacing Model (ASM)/6MMD,No

In [720]:
# Set pandas to display all columns
pd.set_option('display.max_columns', None)

# Display the head of the combined dataframe
df_combined.head()

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,WHO,CD4,ARTDoseDays,ARVRegimen,follow_up_status,AdheranceLevel,NutritionalStatus,FunctionalStatus,No_OI,CotrimoxazoleStartDate,cortimoxazole_stop_date,TPT_Type,inhprophylaxis_started_date,InhprophylaxisCompletedDate,TPT_DoseDaysNumberALT,TPT_DoseDaysNumberINH,TPT_Dispensed_Dose,TPT_SideEffect,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD
0,000552850770442ba548fb1bdc6c8d5a,ALERT,M,61.0,49,NaN,2009-10-10,2009-11-26,181,2024-11-07,T1,NaN,180.0,1j (TDF+3TC+DTG),Alive on ART,Good,NaN,Working,NaN,2000-01-02,2000-01-02,NaN,2022-05-18,2022-11-14,NaN,5.0,180.0,No side effects,NaN,Yes,Negative,2024-05-17,Suppressed,NaN,2024-05-06,2024-05-06,Appointment Spacing Model (ASM)/6MMD,No
1,00080b1139174e14abfa31e899bbb7e1,ALERT,M,NaN,51,177.0,2009-12-14,2013-10-10,134,2024-12-10,T1,NaN,30.0,2f,Alive on ART,Good,NaN,Working,No_OI,2018-10-03,2000-01-02,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,Yes,Negative,2024-09-26,Suppressed,NaN,2024-06-20,2024-06-20,NaN,No
2,0018c84fc44a428ba5cc6d0b2b62312e,ALERT,F,63.0,72,163.0,2003-10-26,2003-10-26,254,2024-08-30,T1,NaN,180.0,1e,Alive on ART,Good,Normal,Working,No_OI,2000-01-02,2000-01-02,NaN,2022-02-06,2022-08-05,NaN,5.0,180.0,No side effects,Good,Yes,Negative,2024-03-25,Suppressed,NaN,2024-03-04,2024-03-04,NaN,No
3,001de407f0754eba8f2b577b7636f857,ALERT,M,80.0,53,170.0,2011-03-14,2011-09-05,159,2024-09-07,T1,NaN,180.0,1j (TDF+3TC+DTG),Alive on ART,Good,Overweight,Working,No_OI,2018-08-08,2000-01-02,Alternate,2022-07-13,2022-10-11,2.0,NaN,90.0,No side effects,Good,Yes,Negative,2024-11-01,Suppressed,NaN,2024-09-07,2024-09-07,Appointment Spacing Model (ASM)/6MMD,No
4,001f9d5a3a2d40a190fca88c36f893cf,ALERT,F,63.0,54,153.0,2000-01-02,2015-12-15,108,2024-12-14,T1,NaN,180.0,1j (TDF+3TC+DTG),Alive on ART,Good,Overweight,Working,No_OI,2018-06-18,2000-01-02,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,Yes,Negative,2023-12-26,Suppressed,NaN,2024-12-14,2024-12-14,Appointment Spacing Model (ASM)/6MMD,No

In [721]:
# Replace NaN values in AdheranceLevel with 'Poor'
df_combined['AdheranceLevel'] = df_combined['AdheranceLevel'].fillna('Poor')

# Recategorize 'Fair' as 'Poor'
df_combined['AdheranceLevel'] = df_combined['AdheranceLevel'].replace('Fair', 'Poor')

# Calculate missing values (should be 0 now)
missing_count = df_combined['AdheranceLevel'].isna().sum()
total_count = len(df_combined)
proportion_missing = (missing_count / total_count) * 100

print(f"Missing values in 'AdheranceLevel' after replacement: {missing_count}")
print(f"Proportion of missing values: {proportion_missing:.2f}%\n")

# Calculate frequency and proportion of categories within AdheranceLevel
adherence_counts = df_combined['AdheranceLevel'].value_counts(dropna=False)
adherence_proportions = df_combined['AdheranceLevel'].value_counts(normalize=True, dropna=False) * 100

print("Updated AdheranceLevel Categories - Counts and Proportions:")
summary_df = pd.DataFrame({'Count': adherence_counts, 'Proportion (%)': adherence_proportions})
print(summary_df)

Missing values in 'AdheranceLevel' after replacement: 0
Proportion of missing values: 0.00%

Updated AdheranceLevel Categories - Counts and Proportions:
                Count  Proportion (%)
AdheranceLevel
Good            13659       74.261947
Poor             4734       25.738053

In [722]:
from datetime import datetime

# Calculate the duration in years since HIV confirmation and round to 1 decimal place
today = datetime.now()
df_combined['duration_with_hiv_years'] = ((today - df_combined['date_hiv_confirmed']).dt.days / 365.25).round(1)

# Display the first few rows of the relevant columns
print("Summary of the new duration variable (rounded to 1 decimal):")
display(df_combined[['date_hiv_confirmed', 'duration_with_hiv_years']].head())
print(f"\nAverage duration with HIV: {df_combined['duration_with_hiv_years'].mean():.1f} years")

Summary of the new duration variable (rounded to 1 decimal):

  date_hiv_confirmed  duration_with_hiv_years
0         2009-10-10                     16.7
1         2009-12-14                     16.5
2         2003-10-26                     22.7
3         2011-03-14                     15.3
4         2000-01-02                     26.5

Average duration with HIV: 16.4 years

In [723]:
# Calculate missing counts and proportions for all variables
missing_counts = df_combined.isna().sum()
missing_proportions = (df_combined.isna().mean() * 100).round(2)

# Create a summary table
missing_table = pd.DataFrame({
    'Missing Count': missing_counts,
    'Proportion (%)': missing_proportions
})

# Display the table
print("Missing Value Analysis for All Variables:")
display(missing_table)

Missing Value Analysis for All Variables:

                             Missing Count  Proportion (%)
PatientGUID                              0            0.00
Health_facility                          0            0.00
Sex                                      0            0.00
Weight                                2083           11.32
Age                                      0            0.00
Height                                 916            4.98
date_hiv_confirmed                       0            0.00
art_start_date                           0            0.00
MonthsOnART                              0            0.00
FollowUpDate                             0            0.00
WHO                                   2165           11.77
CD4                                  18303           99.51
ARTDoseDays                              1            0.01
ARVRegimen                              70            0.38
follow_up_status                         0            0.00
AdheranceLevel                           0            0.00
NutritionalStatus                     3430           18.65
FunctionalStatus                      2115           11.50
No_OI                                 6895           37.49
CotrimoxazoleStartDate                   0            0.00
cortimoxazole_stop_date                  0            0.00
TPT_Type                              7506           40.81
inhprophylaxis_started_date           2250           12.23
InhprophylaxisCompletedDate           2408           13.09
TPT_DoseDaysNumberALT                15763           85.70
TPT_DoseDaysNumberINH                13142           71.45
TPT_Dispensed_Dose                   10704           58.20
TPT_SideEffect                        7696           41.84
TPT_Adherence                        16105           87.56
tb_screened                              2            0.01
tb_screening_result                     17            0.09
viral_load_perform_date                  0            0.00
viral_load_status                      366            1.99
viral_load_count                     10344           56.24
VL_Sent_Date                           329            1.79
viral_load_ref_date                      0            0.00
DSD_Category                          5422           29.48
AHD                                      0            0.00
duration_with_hiv_years                  0            0.00

In [724]:
# Calculate the mean for Weight and Height
weight_mean = df_combined['Weight'].mean()
height_mean = df_combined['Height'].mean()

# Impute missing values with the calculated means
df_combined['Weight'] = df_combined['Weight'].fillna(weight_mean)
df_combined['Height'] = df_combined['Height'].fillna(height_mean)

# Verify that there are no more missing values in these columns
print(f"Imputed Weight with mean: {weight_mean:.2f}")
print(f"Imputed Height with mean: {height_mean:.2f}")
print(f"Remaining missing values in 'Weight': {df_combined['Weight'].isna().sum()}")
print(f"Remaining missing values in 'Height': {df_combined['Height'].isna().sum()}")

Imputed Weight with mean: 63.57
Imputed Height with mean: 160.55
Remaining missing values in 'Weight': 0
Remaining missing values in 'Height': 0

In [725]:
# Calculate BMI: Weight(kg) / [Height(m)]^2
# Height is converted from cm to m
df_combined['BMI'] = (df_combined['Weight'] / ((df_combined['Height'] / 100) ** 2)).round(2)

# Display the first few rows of the new variable
print("BMI variable created successfully.")
display(df_combined[['Weight', 'Height', 'BMI']].head())

BMI variable created successfully.

      Weight    Height    BMI
0  61.000000  160.5541  23.66
1  63.570202  177.0000  20.29
2  63.000000  163.0000  23.71
3  80.000000  170.0000  27.68
4  63.000000  153.0000  26.91

In [726]:
# Define the mapping for standardizing WHO stages
who_mapping = {
    'T1': 'WHO Stage I',
    'Stage One': 'WHO Stage I',
    'T2': 'WHO Stage II',
    'Stage Two': 'WHO Stage II',
    'T3': 'WHO Stage III',
    'Stage Three': 'WHO Stage III',
    'T4': 'WHO Stage IV',
    'Stage Four': 'WHO Stage IV'
}

# Apply the mapping to the 'WHO' column
df_combined['WHO'] = df_combined['WHO'].map(who_mapping).fillna(df_combined['WHO'])

# Recalculate and display the updated distribution
who_counts = df_combined['WHO'].value_counts(dropna=False)
who_proportions = (df_combined['WHO'].value_counts(dropna=False, normalize=True) * 100).round(2)

who_summary = pd.DataFrame({
    'Count': who_counts,
    'Proportion (%)': who_proportions
})

print("Standardized Distribution of WHO Categories:")
display(who_summary)

Standardized Distribution of WHO Categories:

               Count  Proportion (%)
WHO
WHO Stage I    16117           87.63
NaN             2165           11.77
WHO Stage IV      67            0.36
WHO Stage III     24            0.13
WHO Stage II      20            0.11

In [727]:
# Define the mapping for recategorizing NutritionalStatus
nutrition_mapping = {
    'Normal': 'Normal',
    'Overweight': 'Overweight/Obese',
    'Obese': 'Overweight/Obese',
    'Mild Malnutrition': 'Undernourished',
    'Moderate Malnutrition': 'Undernourished',
    'Sever Malnutrition': 'Undernourished',
    'SAM': 'Undernourished'
}

# Apply the mapping to the 'NutritionalStatus' column
# fillna(df_combined['NutritionalStatus']) ensures NaNs remain as NaNs
df_combined['NutritionalStatus'] = df_combined['NutritionalStatus'].map(nutrition_mapping).fillna(df_combined['NutritionalStatus'])

# Recalculate and display the updated distribution
nutrition_counts = df_combined['NutritionalStatus'].value_counts(dropna=False)
nutrition_proportions = (df_combined['NutritionalStatus'].value_counts(dropna=False, normalize=True) * 100).round(2)

nutrition_summary = pd.DataFrame({
    'Count': nutrition_counts,
    'Proportion (%)': nutrition_proportions
})

print("Simplified NutritionalStatus Categories:")
display(nutrition_summary)

Simplified NutritionalStatus Categories:

                   Count  Proportion (%)
NutritionalStatus
Normal              7639           41.53
Overweight/Obese    6087           33.09
NaN                 3430           18.65
Undernourished      1237            6.73

In [728]:
# Calculate frequency and proportion of follow_up_status
follow_up_counts = df_combined['follow_up_status'].value_counts(dropna=False)
follow_up_proportions = (df_combined['follow_up_status'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
follow_up_summary = pd.DataFrame({
    'Count': follow_up_counts,
    'Proportion (%)': follow_up_proportions
})

print("Distribution of Follow-up Status:")
display(follow_up_summary)

Distribution of Follow-up Status:

                  Count  Proportion (%)
follow_up_status
Alive on ART      18242           99.18
Restart             150            0.82
TO                    1            0.01

In [729]:
# Calculate frequency and proportion of FunctionalStatus
functional_counts = df_combined['FunctionalStatus'].value_counts(dropna=False)
functional_proportions = (df_combined['FunctionalStatus'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
functional_summary = pd.DataFrame({
    'Count': functional_counts,
    'Proportion (%)': functional_proportions
})

print("Distribution of Functional Status:")
display(functional_summary)

Distribution of Functional Status:

                  Count  Proportion (%)
FunctionalStatus
Working           16075           87.40
NaN                2115           11.50
Ambulatory          163            0.89
Bedridden            40            0.22

In [730]:
# Recategorize No_OI into Opportunistic Infections (Yes/No)
# If No_OI is present, it means No infection. If NaN, consider it Yes.
df_combined['Opportunistic_Infections'] = df_combined['No_OI'].apply(lambda x: 'No' if x == 'No_OI' else 'Yes')

# Calculate frequency and proportion
oi_counts = df_combined['Opportunistic_Infections'].value_counts(dropna=False)
oi_proportions = (df_combined['Opportunistic_Infections'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
oi_summary = pd.DataFrame({
    'Count': oi_counts,
    'Proportion (%)': oi_proportions
})

print("Distribution of Opportunistic Infections (NaN treated as Yes):")
display(oi_summary)

Distribution of Opportunistic Infections (NaN treated as Yes):

                          Count  Proportion (%)
Opportunistic_Infections
No                        11498           62.51
Yes                        6895           37.49

In [731]:
# Calculate frequency and proportion of TPT_Type
tpt_type_counts = df_combined['TPT_Type'].value_counts(dropna=False)
tpt_type_proportions = (df_combined['TPT_Type'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
tpt_type_summary = pd.DataFrame({
    'Count': tpt_type_counts,
    'Proportion (%)': tpt_type_proportions
})

print("Distribution of TPT_Type:")
display(tpt_type_summary)

Distribution of TPT_Type:

            Count  Proportion (%)
TPT_Type
NaN          7506           40.81
INH          6668           36.25
Alternate    4213           22.91
Continuous      6            0.03

In [732]:
# Calculate frequency and proportion of tb_screened
tb_screened_counts = df_combined['tb_screened'].value_counts(dropna=False)
tb_screened_proportions = (df_combined['tb_screened'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
tb_screened_summary = pd.DataFrame({
    'Count': tb_screened_counts,
    'Proportion (%)': tb_screened_proportions
})

print("Distribution of TB Screened Status:")
display(tb_screened_summary)

Distribution of TB Screened Status:

             Count  Proportion (%)
tb_screened
Yes          18391           99.99
NaN              2            0.01

In [733]:
# Calculate frequency and proportion of tb_screening_result
tb_result_counts = df_combined['tb_screening_result'].value_counts(dropna=False)
tb_result_proportions = (df_combined['tb_screening_result'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
tb_result_summary = pd.DataFrame({
    'Count': tb_result_counts,
    'Proportion (%)': tb_result_proportions
})

print("Distribution of TB Screening Results:")
display(tb_result_summary)

Distribution of TB Screening Results:

                     Count  Proportion (%)
tb_screening_result
Negative             18376           99.91
NaN                     17            0.09

In [734]:
from datetime import datetime

# Calculate the duration in years since ART initiation and round to 1 decimal place
today = datetime.now()
df_combined['art_duration_years'] = ((today - df_combined['art_start_date']).dt.days / 365.25).round(1)

# Display the first few rows of the relevant columns
print("Summary of the new ART duration variable (Years):")
display(df_combined[['art_start_date', 'art_duration_years']].head())
print(f"\nAverage ART duration: {df_combined['art_duration_years'].mean():.1f} years")

Summary of the new ART duration variable (Years):

  art_start_date  art_duration_years
0     2009-11-26                16.6
1     2013-10-10                12.7
2     2003-10-26                22.7
3     2011-09-05                14.8
4     2015-12-15                10.5

Average ART duration: 15.1 years

In [735]:
# Define the mapping for viral_load_status recategorization
vl_mapping = {
    'Suppressed': 'Suppressed',
    'Low Level Viremia': 'Suppressed',
    'High VL': 'Unsuppressed',
    'Unsuppressed': 'Unsuppressed'
}

# Apply the mapping
df_combined['viral_load_status'] = df_combined['viral_load_status'].map(vl_mapping).fillna(df_combined['viral_load_status'])

# Calculate frequency and proportion of the new categories
vl_status_counts = df_combined['viral_load_status'].value_counts(dropna=False)
vl_status_proportions = (df_combined['viral_load_status'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
vl_status_summary = pd.DataFrame({
    'Count': vl_status_counts,
    'Proportion (%)': vl_status_proportions
})

print("Recategorized Distribution of Viral Load Status:")
display(vl_status_summary)

Recategorized Distribution of Viral Load Status:

                   Count  Proportion (%)
viral_load_status
Suppressed         17637           95.89
Unsuppressed         390            2.12
NaN                  366            1.99

In [736]:
import numpy as np

# Create a new column: 'Yes' if InhprophylaxisCompletedDate is not null, 'No' otherwise
df_combined['TPT_Completed'] = np.where(df_combined['InhprophylaxisCompletedDate'].notna(), 'Yes', 'No')

# Calculate frequency and proportion
tpt_comp_counts = df_combined['TPT_Completed'].value_counts(dropna=False)
tpt_comp_proportions = (df_combined['TPT_Completed'].value_counts(normalize=True) * 100).round(2)

# Create summary table
tpt_comp_summary = pd.DataFrame({
    'Count': tpt_comp_counts,
    'Proportion (%)': tpt_comp_proportions
})

print("Frequency Distribution of TPT Completion Status:")
display(tpt_comp_summary)

Frequency Distribution of TPT Completion Status:

               Count  Proportion (%)
TPT_Completed
Yes            15985           86.91
No              2408           13.09

In [737]:
# Calculate frequency and proportion of AHD status
ahd_counts = df_combined['AHD'].value_counts(dropna=False)
ahd_proportions = (df_combined['AHD'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
ahd_summary = pd.DataFrame({
    'Count': ahd_counts,
    'Proportion (%)': ahd_proportions
})

print("Distribution of Advanced HIV Disease (AHD):")
display(ahd_summary)

Distribution of Advanced HIV Disease (AHD):

     Count  Proportion (%)
AHD
No   18248           99.21
Yes    145            0.79

In [738]:
# Define the recategorization function for ARTDoseDays
def categorize_refill(days):
    if pd.isna(days):
        return 'Missing'
    elif days <= 89:
        return 'Short refill'
    elif days >= 90:
        return 'Multi-month dispensing (MMD)'
    return 'Other'

# Apply the recategorization to a new column 'Refill_Category'
df_combined['Refill_Category'] = df_combined['ARTDoseDays'].apply(categorize_refill)

# Calculate frequency and proportion of the new 'Refill_Category'
refill_counts = df_combined['Refill_Category'].value_counts(dropna=False)
refill_proportions = (df_combined['Refill_Category'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create summary table
refill_summary = pd.DataFrame({
    'Count': refill_counts,
    'Proportion (%)': refill_proportions
})

print("Recategorized Distribution of Refill Category:")
display(refill_summary)

Recategorized Distribution of Refill Category:

                              Count  Proportion (%)
Refill_Category
Multi-month dispensing (MMD)  15519           84.37
Short refill                   2873           15.62
Missing                           1            0.01

In [739]:
# Calculate missing counts and proportions for all variables
missing_counts = df_combined.isna().sum()
missing_proportions = (df_combined.isna().mean() * 100).round(2)

# Create a summary table
missing_table = pd.DataFrame({
    'Missing Count': missing_counts,
    'Proportion (%)': missing_proportions
})

# Display the table
print("Missing Value Analysis for All Variables:")
display(missing_table)

Missing Value Analysis for All Variables:

                             Missing Count  Proportion (%)
PatientGUID                              0            0.00
Health_facility                          0            0.00
Sex                                      0            0.00
Weight                                   0            0.00
Age                                      0            0.00
Height                                   0            0.00
date_hiv_confirmed                       0            0.00
art_start_date                           0            0.00
MonthsOnART                              0            0.00
FollowUpDate                             0            0.00
WHO                                   2165           11.77
CD4                                  18303           99.51
ARTDoseDays                              1            0.01
ARVRegimen                              70            0.38
follow_up_status                         0            0.00
AdheranceLevel                           0            0.00
NutritionalStatus                     3430           18.65
FunctionalStatus                      2115           11.50
No_OI                                 6895           37.49
CotrimoxazoleStartDate                   0            0.00
cortimoxazole_stop_date                  0            0.00
TPT_Type                              7506           40.81
inhprophylaxis_started_date           2250           12.23
InhprophylaxisCompletedDate           2408           13.09
TPT_DoseDaysNumberALT                15763           85.70
TPT_DoseDaysNumberINH                13142           71.45
TPT_Dispensed_Dose                   10704           58.20
TPT_SideEffect                        7696           41.84
TPT_Adherence                        16105           87.56
tb_screened                              2            0.01
tb_screening_result                     17            0.09
viral_load_perform_date                  0            0.00
viral_load_status                      366            1.99
viral_load_count                     10344           56.24
VL_Sent_Date                           329            1.79
viral_load_ref_date                      0            0.00
DSD_Category                          5422           29.48
AHD                                      0            0.00
duration_with_hiv_years                  0            0.00
BMI                                      0            0.00
Opportunistic_Infections                 0            0.00
art_duration_years                       0            0.00
TPT_Completed                            0            0.00
Refill_Category                          0            0.00

In [740]:
df_combined.head()

,PatientGUID,Health_facility,Sex,Weight,Age,Height,date_hiv_confirmed,art_start_date,MonthsOnART,FollowUpDate,WHO,CD4,ARTDoseDays,ARVRegimen,follow_up_status,AdheranceLevel,NutritionalStatus,FunctionalStatus,No_OI,CotrimoxazoleStartDate,cortimoxazole_stop_date,TPT_Type,inhprophylaxis_started_date,InhprophylaxisCompletedDate,TPT_DoseDaysNumberALT,TPT_DoseDaysNumberINH,TPT_Dispensed_Dose,TPT_SideEffect,TPT_Adherence,tb_screened,tb_screening_result,viral_load_perform_date,viral_load_status,viral_load_count,VL_Sent_Date,viral_load_ref_date,DSD_Category,AHD,duration_with_hiv_years,BMI,Opportunistic_Infections,art_duration_years,TPT_Completed,Refill_Category
0,000552850770442ba548fb1bdc6c8d5a,ALERT,M,61.000000,49,160.5541,2009-10-10,2009-11-26,181,2024-11-07,WHO Stage I,NaN,180.0,1j (TDF+3TC+DTG),Alive on ART,Good,NaN,Working,NaN,2000-01-02,2000-01-02,NaN,2022-05-18,2022-11-14,NaN,5.0,180.0,No side effects,NaN,Yes,Negative,2024-05-17,Suppressed,NaN,2024-05-06,2024-05-06,Appointment Spacing Model (ASM)/6MMD,No,16.7,23.66,Yes,16.6,Yes,Multi-month dispensing (MMD)
1,00080b1139174e14abfa31e899bbb7e1,ALERT,M,63.570202,51,177.0000,2009-12-14,2013-10-10,134,2024-12-10,WHO Stage I,NaN,30.0,2f,Alive on ART,Good,NaN,Working,No_OI,2018-10-03,2000-01-02,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,Yes,Negative,2024-09-26,Suppressed,NaN,2024-06-20,2024-06-20,NaN,No,16.5,20.29,No,12.7,No,Short refill
2,0018c84fc44a428ba5cc6d0b2b62312e,ALERT,F,63.000000,72,163.0000,2003-10-26,2003-10-26,254,2024-08-30,WHO Stage I,NaN,180.0,1e,Alive on ART,Good,Normal,Working,No_OI,2000-01-02,2000-01-02,NaN,2022-02-06,2022-08-05,NaN,5.0,180.0,No side effects,Good,Yes,Negative,2024-03-25,Suppressed,NaN,2024-03-04,2024-03-04,NaN,No,22.7,23.71,No,22.7,Yes,Multi-month dispensing (MMD)
3,001de407f0754eba8f2b577b7636f857,ALERT,M,80.000000,53,170.0000,2011-03-14,2011-09-05,159,2024-09-07,WHO Stage I,NaN,180.0,1j (TDF+3TC+DTG),Alive on ART,Good,Overweight/Obese,Working,No_OI,2018-08-08,2000-01-02,Alternate,2022-07-13,2022-10-11,2.0,NaN,90.0,No side effects,Good,Yes,Negative,2024-11-01,Suppressed,NaN,2024-09-07,2024-09-07,Appointment Spacing Model (ASM)/6MMD,No,15.3,27.68,No,14.8,Yes,Multi-month dispensing (MMD)
4,001f9d5a3a2d40a190fca88c36f893cf,ALERT,F,63.000000,54,153.0000,2000-01-02,2015-12-15,108,2024-12-14,WHO Stage I,NaN,180.0,1j (TDF+3TC+DTG),Alive on ART,Good,Overweight/Obese,Working,No_OI,2018-06-18,2000-01-02,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,Yes,Negative,2023-12-26,Suppressed,NaN,2024-12-14,2024-12-14,Appointment Spacing Model (ASM)/6MMD,No,26.5,26.91,No,10.5,No,Multi-month dispensing (MMD)

In [741]:
df_combined.columns

Index(['PatientGUID', 'Health_facility', 'Sex', 'Weight', 'Age', 'Height',
       'date_hiv_confirmed', 'art_start_date', 'MonthsOnART', 'FollowUpDate',
       'WHO', 'CD4', 'ARTDoseDays', 'ARVRegimen', 'follow_up_status',
       'AdheranceLevel', 'NutritionalStatus', 'FunctionalStatus', 'No_OI',
       'CotrimoxazoleStartDate', 'cortimoxazole_stop_date', 'TPT_Type',
       'inhprophylaxis_started_date', 'InhprophylaxisCompletedDate',
       'TPT_DoseDaysNumberALT', 'TPT_DoseDaysNumberINH', 'TPT_Dispensed_Dose',
       'TPT_SideEffect', 'TPT_Adherence', 'tb_screened', 'tb_screening_result',
       'viral_load_perform_date', 'viral_load_status', 'viral_load_count',
       'VL_Sent_Date', 'viral_load_ref_date', 'DSD_Category', 'AHD',
       'duration_with_hiv_years', 'BMI', 'Opportunistic_Infections',
       'art_duration_years', 'TPT_Completed', 'Refill_Category'],
      dtype='object')

In [742]:
selected_final_columns = [
    'Health_facility', 'Sex', 'Age', 'BMI','duration_with_hiv_years', 'art_duration_years', 'WHO', 'ARVRegimen',
     'NutritionalStatus','FunctionalStatus','viral_load_status', 'Opportunistic_Infections', 'TPT_Completed',
    'Refill_Category','AdheranceLevel',
]

df_selected = df_combined[selected_final_columns]
print("Selected columns from df_combined:")
df_selected.head()

Selected columns from df_combined:

,Health_facility,Sex,Age,BMI,duration_with_hiv_years,art_duration_years,WHO,ARVRegimen,NutritionalStatus,FunctionalStatus,viral_load_status,Opportunistic_Infections,TPT_Completed,Refill_Category,AdheranceLevel
0,ALERT,M,49,23.66,16.7,16.6,WHO Stage I,1j (TDF+3TC+DTG),NaN,Working,Suppressed,Yes,Yes,Multi-month dispensing (MMD),Good
1,ALERT,M,51,20.29,16.5,12.7,WHO Stage I,2f,NaN,Working,Suppressed,No,No,Short refill,Good
2,ALERT,F,72,23.71,22.7,22.7,WHO Stage I,1e,Normal,Working,Suppressed,No,Yes,Multi-month dispensing (MMD),Good
3,ALERT,M,53,27.68,15.3,14.8,WHO Stage I,1j (TDF+3TC+DTG),Overweight/Obese,Working,Suppressed,No,Yes,Multi-month dispensing (MMD),Good
4,ALERT,F,54,26.91,26.5,10.5,WHO Stage I,1j (TDF+3TC+DTG),Overweight/Obese,Working,Suppressed,No,No,Multi-month dispensing (MMD),Good

In [743]:
# Calculate missing counts and proportions for all variables
missing_counts = df_selected.isna().sum()
missing_proportions = (df_selected.isna().mean() * 100).round(2)

# Create a summary table
missing_table = pd.DataFrame({
    'Missing Count': missing_counts,
    'Proportion (%)': missing_proportions
})

# Display the table
print("Missing Value Analysis for All Variables:")
display(missing_table)

Missing Value Analysis for All Variables:

                          Missing Count  Proportion (%)
Health_facility                       0            0.00
Sex                                   0            0.00
Age                                   0            0.00
BMI                                   0            0.00
duration_with_hiv_years               0            0.00
art_duration_years                    0            0.00
WHO                                2165           11.77
ARVRegimen                           70            0.38
NutritionalStatus                  3430           18.65
FunctionalStatus                   2115           11.50
viral_load_status                   366            1.99
Opportunistic_Infections              0            0.00
TPT_Completed                         0            0.00
Refill_Category                       0            0.00
AdheranceLevel                        0            0.00

In [744]:
print("Original Missing Value Analysis for df_selected before new imputation strategy:")
original_missing_counts = df_selected.isna().sum()
original_missing_proportions = (df_selected.isna().mean() * 100).round(2)
original_missing_table = pd.DataFrame({'Missing Count': original_missing_counts, 'Proportion (%)': original_missing_proportions})
display(original_missing_table[original_missing_table['Missing Count'] > 0])


# Identify numerical and categorical columns with missing values
missing_numerical_cols = df_selected.select_dtypes(include=['number']).columns[df_selected.select_dtypes(include=['number']).isna().any()].tolist()
missing_categorical_cols = df_selected.select_dtypes(include=['object', 'category']).columns[df_selected.select_dtypes(include=['object', 'category']).isna().any()].tolist()

print("\n--- Applying New Imputation Strategy ---")

# Impute missing numerical values with the mean
for col in missing_numerical_cols:
    if col in df_selected.columns:
        mean_value = df_selected[col].mean()
        df_selected[col].fillna(mean_value, inplace=True)
        print(f"'{col}' missing values imputed with mean: {mean_value:.2f}")

# Impute missing categorical values with the mode
for col in missing_categorical_cols:
    if col in df_selected.columns:
        if df_selected[col].isnull().all(): # Handle case where all values are NaN
            mode_value = 'Unknown' # Fallback if no mode can be determined
        else:
            mode_value = df_selected[col].mode()[0] # Get the most frequent value
        df_selected[col].fillna(mode_value, inplace=True)
        print(f"'{col}' missing values imputed with mode: {mode_value}")

# Verify that all identified missing values have been handled
print("\nMissing Value Analysis for df_selected after new imputation:")
missing_counts_after_imputation = df_selected.isna().sum()
missing_proportions_after_imputation = (df_selected.isna().mean() * 100).round(2)

missing_table_after_imputation = pd.DataFrame({
    'Missing Count': missing_counts_after_imputation,
    'Proportion (%)': missing_proportions_after_imputation
})

display(missing_table_after_imputation[missing_table_after_imputation['Missing Count'] > 0])

Original Missing Value Analysis for df_selected before new imputation strategy:

                   Missing Count  Proportion (%)
WHO                         2165           11.77
ARVRegimen                    70            0.38
NutritionalStatus           3430           18.65
FunctionalStatus            2115           11.50
viral_load_status            366            1.99

--- Applying New Imputation Strategy ---
'WHO' missing values imputed with mode: WHO Stage I
'ARVRegimen' missing values imputed with mode: 1j (TDF+3TC+DTG)
'NutritionalStatus' missing values imputed with mode: Normal
'FunctionalStatus' missing values imputed with mode: Working
'viral_load_status' missing values imputed with mode: Suppressed

Missing Value Analysis for df_selected after new imputation:

/tmp/ipykernel_2725/2360319169.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_selected[col].fillna(mode_value, inplace=True)
/tmp/ipykernel_2725/2360319169.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected[col].fillna(mode_value, inplace=True)

Empty DataFrame
Columns: [Missing Count, Proportion (%)]
Index: []

In [745]:
# Calculate missing counts and proportions for all variables
missing_counts = df_selected.isna().sum()
missing_proportions = (df_selected.isna().mean() * 100).round(2)

# Create a summary table
missing_table = pd.DataFrame({
    'Missing Count': missing_counts,
    'Proportion (%)': missing_proportions
})

# Display the table
print("Missing Value Analysis for All Variables:")
display(missing_table)

Missing Value Analysis for All Variables:

                          Missing Count  Proportion (%)
Health_facility                       0             0.0
Sex                                   0             0.0
Age                                   0             0.0
BMI                                   0             0.0
duration_with_hiv_years               0             0.0
art_duration_years                    0             0.0
WHO                                   0             0.0
ARVRegimen                            0             0.0
NutritionalStatus                     0             0.0
FunctionalStatus                      0             0.0
viral_load_status                     0             0.0
Opportunistic_Infections              0             0.0
TPT_Completed                         0             0.0
Refill_Category                       0             0.0
AdheranceLevel                        0             0.0

In [746]:
df_adult = df_selected[df_selected['Age'] >= 18]

print("Entries where Age is 18 or older:")
display(df_adult.head())
print(f"Total entries with Age 18 or older: {len(df_adult)}")

Entries where Age is 18 or older:

,Health_facility,Sex,Age,BMI,duration_with_hiv_years,art_duration_years,WHO,ARVRegimen,NutritionalStatus,FunctionalStatus,viral_load_status,Opportunistic_Infections,TPT_Completed,Refill_Category,AdheranceLevel
0,ALERT,M,49,23.66,16.7,16.6,WHO Stage I,1j (TDF+3TC+DTG),Normal,Working,Suppressed,Yes,Yes,Multi-month dispensing (MMD),Good
1,ALERT,M,51,20.29,16.5,12.7,WHO Stage I,2f,Normal,Working,Suppressed,No,No,Short refill,Good
2,ALERT,F,72,23.71,22.7,22.7,WHO Stage I,1e,Normal,Working,Suppressed,No,Yes,Multi-month dispensing (MMD),Good
3,ALERT,M,53,27.68,15.3,14.8,WHO Stage I,1j (TDF+3TC+DTG),Overweight/Obese,Working,Suppressed,No,Yes,Multi-month dispensing (MMD),Good
4,ALERT,F,54,26.91,26.5,10.5,WHO Stage I,1j (TDF+3TC+DTG),Overweight/Obese,Working,Suppressed,No,No,Multi-month dispensing (MMD),Good

Total entries with Age 18 or older: 17669

In [747]:
# Define bins and labels for recategorization of 'duration_with_hiv_years'
bins = [-float('inf'), 5, 10, float('inf')]
labels = ['<5 years', '5–9 years', '≥10 years']

# Create the new categorical column
df_adult['duration_with_hiv_years'] = pd.cut(df_selected['duration_with_hiv_years'], bins=bins, labels=labels, right=False)

# Calculate frequency and proportion of the new category
duration_category_counts = df_adult['duration_with_hiv_years'].value_counts(dropna=False)
duration_category_proportions = (df_adult['duration_with_hiv_years'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create a summary table
duration_category_summary = pd.DataFrame({
    'Count': duration_category_counts,
    'Proportion (%)': duration_category_proportions
})

print("Recategorized Distribution of Duration with HIV:")
display(duration_category_summary)

Recategorized Distribution of Duration with HIV:

/tmp/ipykernel_2725/2577921128.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adult['duration_with_hiv_years'] = pd.cut(df_selected['duration_with_hiv_years'], bins=bins, labels=labels, right=False)

                         Count  Proportion (%)
duration_with_hiv_years
≥10 years                15209           86.08
5–9 years                 1566            8.86
<5 years                   894            5.06

In [748]:
# Define bins and labels for recategorization of 'art_duration_years'
art_bins = [-float('inf'), 2, 5, float('inf')]
art_labels = ['<2 years', '2–5 years', '>5 years']

# Create the new categorical column
df_adult['art_duration_years'] = pd.cut(df_adult['art_duration_years'], bins=art_bins, labels=art_labels, right=False)

# Calculate frequency and proportion of the new category
art_duration_category_counts = df_adult['art_duration_years'].value_counts(dropna=False)
art_duration_category_proportions = (df_adult['art_duration_years'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create a summary table
art_duration_category_summary = pd.DataFrame({
    'Count': art_duration_category_counts,
    'Proportion (%)': art_duration_category_proportions
})

print("Recategorized Distribution of ART Duration:")
display(art_duration_category_summary)

Recategorized Distribution of ART Duration:

/tmp/ipykernel_2725/833446439.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adult['art_duration_years'] = pd.cut(df_adult['art_duration_years'], bins=art_bins, labels=art_labels, right=False)

                    Count  Proportion (%)
art_duration_years
>5 years            16694           94.48
2–5 years             833            4.71
<2 years              142            0.80

In [749]:
import pandas as pd

# Define bins and labels for recategorization of 'BMI'
# The ranges are < 18.5, 18.5–24.9, 25.0–29.9, ≥ 30.0
# pd.cut with right=False means the intervals are [left, right)
bmi_bins = [-float('inf'), 18.5, 25.0, 30.0, float('inf')]
bmi_labels = ['Underweight', 'Normal', 'Overweight', 'Obese']

# Create the new categorical column
df_adult['BMI'] = pd.cut(df_adult['BMI'], bins=bmi_bins, labels=bmi_labels, right=False)

# Calculate frequency and proportion of the new category
bmi_category_counts = df_adult['BMI'].value_counts(dropna=False)
bmi_category_proportions = (df_adult['BMI'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create a summary table
bmi_category_summary = pd.DataFrame({
    'Count': bmi_category_counts,
    'Proportion (%)': bmi_category_proportions
})

print("Recategorized Distribution of BMI:")
display(bmi_category_summary)

Recategorized Distribution of BMI:

/tmp/ipykernel_2725/3101376739.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adult['BMI'] = pd.cut(df_adult['BMI'], bins=bmi_bins, labels=bmi_labels, right=False)

             Count  Proportion (%)
BMI
Normal        9193           52.03
Overweight    5291           29.95
Obese         1844           10.44
Underweight   1341            7.59

In [750]:
# Define bins and labels for recategorization of 'Age'
# The ranges are 18–34, 35–49, and ≥50
# pd.cut with right=False means the intervals are [left, right)
age_bins = [18, 35, 50, float('inf')]
age_labels = ['18–34', '35–49', '≥50']

# Create the new categorical column
df_adult['Age'] = pd.cut(df_adult['Age'], bins=age_bins, labels=age_labels, right=False)

# Calculate frequency and proportion of the new category
age_category_counts = df_adult['Age'].value_counts(dropna=False)
age_category_proportions = (df_adult['Age'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create a summary table
age_category_summary = pd.DataFrame({
    'Count': age_category_counts,
    'Proportion (%)': age_category_proportions
})

print("Recategorized Distribution of Age:")
display(age_category_summary)

Recategorized Distribution of Age:

/tmp/ipykernel_2725/3277671164.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adult['Age'] = pd.cut(df_adult['Age'], bins=age_bins, labels=age_labels, right=False)

       Count  Proportion (%)
Age
≥50     7784           44.05
35–49   7173           40.60
18–34   2712           15.35

In [751]:
df_adult.head()

,Health_facility,Sex,Age,BMI,duration_with_hiv_years,art_duration_years,WHO,ARVRegimen,NutritionalStatus,FunctionalStatus,viral_load_status,Opportunistic_Infections,TPT_Completed,Refill_Category,AdheranceLevel
0,ALERT,M,35–49,Normal,≥10 years,>5 years,WHO Stage I,1j (TDF+3TC+DTG),Normal,Working,Suppressed,Yes,Yes,Multi-month dispensing (MMD),Good
1,ALERT,M,≥50,Normal,≥10 years,>5 years,WHO Stage I,2f,Normal,Working,Suppressed,No,No,Short refill,Good
2,ALERT,F,≥50,Normal,≥10 years,>5 years,WHO Stage I,1e,Normal,Working,Suppressed,No,Yes,Multi-month dispensing (MMD),Good
3,ALERT,M,≥50,Overweight,≥10 years,>5 years,WHO Stage I,1j (TDF+3TC+DTG),Overweight/Obese,Working,Suppressed,No,Yes,Multi-month dispensing (MMD),Good
4,ALERT,F,≥50,Overweight,≥10 years,>5 years,WHO Stage I,1j (TDF+3TC+DTG),Overweight/Obese,Working,Suppressed,No,No,Multi-month dispensing (MMD),Good

In [752]:
import numpy as np

# Define the mapping for ARV Regimen recategorization based on user's input
arv_mapping = {
    # First-line Regimens
    '1j (TDF+3TC+DTG)': 'First-line',
    '1j - TDF+3TC+DTG': 'First-line',
    '1e - TDF+3TC+EFV': 'First-line',
    '1e': 'First-line',
    '1k (AZT+3TC+DTG)': 'First-line',
    '1k - AZT+3TC+DTG': 'First-line',
    '1i - Other Adult 1st line regimen': 'First-line',
    'Other Adult first line regimen': 'First-line',
    '1d': 'First-line',
    '1d - AZT+3TC+EFV': 'First-line',
    '1g': 'First-line',
    '1g - ABC+3TC+EFV': 'First-line',
    '4i (TDF+3TC+DTG)': 'First-line',
    '4i - TDF+3TC+DTG': 'First-line',
    '4j (ABC+3TC+DTG)': 'First-line',
    '4j - ABC+3TC+DTG': 'First-line',
    '4k (AZT+3TC+DTG)': 'First-line',
    '4k - AZT+3TC+DTG': 'First-line',
    '5m (ABC+3TC+DTG)': 'First-line',

    # Second-line Regimens
    '2h': 'Second-line',
    '2h - TDF+3TC+ATV/r': 'Second-line',
    '2f': 'Second-line',
    '2f - AZT+3TC+ATV/r': 'Second-line',
    '2L - Other Adult 2nd line regimen': 'Second-line',
    'Other Adult second line regimen': 'Second-line',
    '2i': 'Second-line',
    '2i - ABC+3TC+LPV/r': 'Second-line',
    '2g': 'Second-line',
    '2g - TDF+3TC+LPV/r': 'Second-line',
    '2e': 'Second-line',
    '2e - AZT+3TC+LPV/r': 'Second-line',
    '2j - TDF+3TC+DTG': 'Second-line',
    '2k - AZT+3TC+DTG': 'Second-line',
    'Other Children second line regimen': 'Second-line',
    '5j': 'Second-line',
    '5j - Other Child 2nd line regimen': 'Second-line',

    # Third-line Regimens
    '3a': 'Third-line',
    '3a - DRV/r+DTG+AZT+3TC': 'Third-line',
    '3b': 'Third-line',
    '3b - DRV/r+DTG+TDF+3TC': 'Third-line',
    '3c - DRV/r+ABC+3TC+DTG': 'Third-line',
    '3d - Other Adult 3rd line regimen': 'Third-line',
    'Other Adult third line regimen': 'Third-line',
    '6f (DRV/r+DTG+ABC+3TC)': 'Third-line',
    '6d': 'Third-line'
}

# Apply the mapping to df_adult['ARVRegimen'] using .loc to prevent SettingWithCopyWarning
df_adult.loc[:, 'ARVRegimen'] = df_adult['ARVRegimen'].map(arv_mapping)

# Recalculate distribution for the newly categorized ARVRegimen, including NaN values
arv_category_counts = df_adult['ARVRegimen'].value_counts(dropna=False)
arv_category_proportions = (df_adult['ARVRegimen'].value_counts(dropna=False, normalize=True) * 100).round(2)

# Create a summary table
arv_category_summary = pd.DataFrame({
    'Count': arv_category_counts,
    'Proportion (%)': arv_category_proportions
})

print("Recategorized Distribution of ARV Regimen:")
display(arv_category_summary)

Recategorized Distribution of ARV Regimen:

             Count  Proportion (%)
ARVRegimen
First-line   15357           86.91
Second-line   2059           11.65
Third-line     141            0.80
NaN            112            0.63

In [755]:
import pandas as pd

# Impute missing values (NaN) in df_adult with the mode for each categorical column
categorical_cols = [
    'Health_facility',
    'Sex',
    'Age',
    'BMI',
    'duration_with_hiv_years',
    'art_duration_years',
    'WHO',
    'ARVRegimen',
    #'NutritionalStatus',
    'FunctionalStatus',
    'viral_load_status',
    'Opportunistic_Infections',
    'TPT_Completed',
    'Refill_Category',
    'AdheranceLevel'
]

for col in categorical_cols:
    if df_adult[col].isnull().any():
        # Calculate the mode and fill NaNs
        col_mode = df_adult[col].mode()[0]
        df_adult[col] = df_adult[col].fillna(col_mode)
        print(f"Imputed missing values in '{col}' with mode: {col_mode}")

descriptive_data = []

for col in categorical_cols:
    counts = df_adult[col].value_counts(dropna=False)
    proportions = df_adult[col].value_counts(dropna=False, normalize=True) * 100

    for category, count in counts.items():
        proportion = proportions[category]
        descriptive_data.append([
            col,
            category,
            count,
            f"{proportion:.2f}%"
        ])

descriptive_table = pd.DataFrame(descriptive_data, columns=['Variables', 'Categories', 'Frequency', 'Percentage within variable'])

# Set pandas options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

display(descriptive_table)

# Reset display options to default
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

,Variables,Categories,Frequency,Percentage within variable
0,Health_facility,Zewuditu,7410,41.94%
1,Health_facility,ALERT,7117,40.28%
2,Health_facility,Yekatit,3142,17.78%
3,Sex,F,10685,60.47%
4,Sex,M,6984,39.53%
5,Age,≥50,7784,44.05%
6,Age,35–49,7173,40.60%
7,Age,18–34,2712,15.35%
8,BMI,Normal,9193,52.03%
9,BMI,Overweight,5291,29.95%
10,BMI,Obese,1844,10.44%
11,BMI,Underweight,1341,7.59%
12,duration_with_hiv_years,≥10 years,15209,86.08%
13,duration_with_hiv_years,5–9 years,1566,8.86%
14,duration_with_hiv_years,<5 years,894,5.06%
15,art_duration_years,>5 years,16694,94.48%
16,art_duration_years,2–5 years,833,4.71%
17,art_duration_years,<2 years,142,0.80%
18,WHO,WHO Stage I,17563,99.40%
19,WHO,WHO Stage IV,64,0.36%
20,WHO,WHO Stage III,23,0.13%
21,WHO,WHO Stage II,19,0.11%
22,ARVRegimen,First-line,15469,87.55%
23,ARVRegimen,Second-line,2059,11.65%
24,ARVRegimen,Third-line,141,0.80%
25,FunctionalStatus,Working,17521,99.16%
26,FunctionalStatus,Ambulatory,108,0.61%
27,FunctionalStatus,Bedridden,40,0.23%
28,viral_load_status,Suppressed,17309,97.96%
29,viral_load_status,Unsuppressed,360,2.04%
30,Opportunistic_Infections,No,11226,63.54%
31,Opportunistic_Infections,Yes,6443,36.46%
32,TPT_Completed,Yes,15379,87.04%
33,TPT_Completed,No,2290,12.96%
34,Refill_Category,Multi-month dispensing (MMD),15178,85.90%
35,Refill_Category,Short refill,2490,14.09%
36,Refill_Category,Missing,1,0.01%
37,AdheranceLevel,Good,13149,74.42%
38,AdheranceLevel,Poor,4520,25.58%